name: MyTestRun

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "test";
  test:
    runs-on: ubuntu-22.04
    if: ${{ false }}
    steps:
    - run: exit 1
  test2:
    runs-on: ubuntu-22.04
    steps:
    - run: echo "test2";
  test3:
    needs: [ test,test2 ]
    runs-on: ubuntu-22.04
    steps:
    - run: echo "done
    
